"""Regression tests pinned to live-Breach (matlab-run) ground truth.

The CSVs under ``tests/breach_matlab_run/`` are verbatim copies of the
2026-06-05 dockerized Breach 1.11.4 / MATLAB R2022b run that produced
``extra/experiments/e1_divergence/cache/breach_column/`` (provenance in
``breach_meta.txt``). They pin the two BreachBackend mimicry behaviors
that the recorded ``tests/breach_ground_truth/`` suite cannot
distinguish:

- BigM equality predicates (``div_equality``): Breach evaluates
  ``x[t] == 3`` to +/-10000 by satisfaction sign, not a metric distance.
- Samples-only window reduction on non-uniform grids
  (``div_nonuniform_always``): Breach does not interpolate the signal
  at window endpoints when the window contains sample points.

Unlike ``tests/breach_ground_truth/`` (regenerated byte-identically by
``generate_ground_truth.m``), these fixtures are frozen copies; they
change only with a new verified MATLAB run.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

from tests._helpers.breach_compat import assert_breach_compatible
from tidystl import Signal, parse

MATLAB_RUN = Path(__file__).parent / "breach_matlab_run"


class TestBreachMatlabRun:
    def test_equality_bigm(self) -> None:
        """x == 3: Breach BigM sign semantics (+/-10000), not -|x-3|."""
        sig = Signal.from_dict(
            times=np.array([0, 1, 2, 3, 4], dtype=float),
            values={"x": np.array([[3, 2, 4, 3, 1]], dtype=float)},
        )
        phi = parse("x == 3")
        assert_breach_compatible(phi, sig, MATLAB_RUN / "div_equality.csv")

    def test_nonuniform_window_samples_only(self) -> None:
        """G[0,1] on a non-uniform grid: samples-only window minimum.

        At t=1.5 the window [1.5, 2.5] contains only the sample at
        t=1.5; Breach reports that sample's value (1), not the PL
        minimum including the interpolated right endpoint (-1).
        """
        sig = Signal.from_dict(
            times=np.array([0.0, 0.5, 1.5, 3.0, 4.0]),
            values={"x": np.array([[0.0, 3.0, 1.0, -2.0, 2.0]])},
        )
        phi = parse("G[0,1](x > 0)")
        assert_breach_compatible(phi, sig, MATLAB_RUN / "div_nonuniform_always.csv")
