"""Sphinx configuration for the tidySTL documentation.

Build with ``sphinx-build -b html docs docs/_build/html`` (or ``-W`` to treat
warnings as errors, as CI does). The narrative pages are MyST Markdown; the
API reference is generated by ``autodoc`` from the installed ``tidystl``
package, and ``linkcode`` wires each documented object back to its source on
GitHub.
"""

from __future__ import annotations

import inspect
import os
import subprocess
import sys
from pathlib import Path

# -- Paths -------------------------------------------------------------------

DOCS_DIR = Path(__file__).resolve().parent
REPO_ROOT = DOCS_DIR.parent

# autodoc imports the installed packages directly; the ``docs`` dependency group
# installs ``tidystl`` and ``tidystl-compat`` as editable workspace members.

# -- Project information -----------------------------------------------------

project = "tidySTL"
author = "tidySTL authors"
copyright = "2026, tidySTL authors"

try:
    from importlib.metadata import version as _pkg_version

    release = _pkg_version("tidystl")
except Exception:  # pragma: no cover - docs still build without metadata
    release = ""
version = release

# -- General configuration ---------------------------------------------------

extensions = [
    "myst_parser",
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.linkcode",
    "sphinx.ext.intersphinx",
]

root_doc = "index"
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# -- MyST --------------------------------------------------------------------

myst_enable_extensions = [
    "colon_fence",
    "deflist",
    "linkify",
    "smartquotes",
]
# Auto-generate anchors for headings so in-page links like ``#references`` work.
myst_heading_anchors = 3

# -- autodoc / napoleon ------------------------------------------------------

autodoc_default_options = {
    "members": True,
    "show-inheritance": True,
    "member-order": "bysource",
}
autodoc_typehints = "description"
autodoc_member_order = "bysource"
autoclass_content = "class"

napoleon_google_docstring = True
napoleon_numpy_docstring = False
napoleon_include_init_with_doc = False
napoleon_use_rtype = True

# -- intersphinx -------------------------------------------------------------

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "numpy": ("https://numpy.org/doc/stable", None),
}

# -- HTML output (Furo) ------------------------------------------------------

html_theme = "furo"
html_title = "tidySTL"
html_theme_options = {
    "source_repository": "https://github.com/midoriao/tidystl/",
    "source_branch": "main",
    "source_directory": "docs/",
}

# -- linkcode ----------------------------------------------------------------

_GITHUB_REPO = "https://github.com/midoriao/tidystl"


def _git_ref() -> str:
    """Resolve the git ref to link against, preferring an exact tag."""
    env_ref = os.environ.get("GITHUB_SHA")
    try:
        tag = subprocess.run(
            ["git", "describe", "--tags", "--exact-match"],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
        if tag:
            return tag
    except Exception:
        pass
    if env_ref:
        return env_ref
    try:
        return subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
    except Exception:
        return "main"


_LINKCODE_REF = _git_ref()


def linkcode_resolve(domain: str, info: dict[str, object]) -> str | None:
    """Map a documented Python object to its source URL on GitHub."""
    if domain != "py" or not info.get("module"):
        return None

    module_name = str(info["module"])
    fullname = str(info["fullname"])

    module = sys.modules.get(module_name)
    if module is None:
        return None

    obj: object = module
    for part in fullname.split("."):
        obj = getattr(obj, part, None)
        if obj is None:
            return None

    # Unwrap decorators / descriptors to reach the underlying function.
    obj = inspect.unwrap(obj) if callable(obj) else obj

    try:
        source_file = inspect.getsourcefile(obj)  # type: ignore[arg-type]
    except TypeError:
        return None
    if source_file is None:
        return None

    try:
        lines, start = inspect.getsourcelines(obj)  # type: ignore[arg-type]
    except (OSError, TypeError):
        return None

    try:
        rel_path = Path(source_file).resolve().relative_to(REPO_ROOT)
    except ValueError:
        # Object lives outside the repo (e.g. an installed copy); fall back to
        # the known package layout.
        rel_path = Path("packages/tidystl/src") / Path(*module_name.split("."))
        rel_path = rel_path.with_suffix(".py")

    end = start + len(lines) - 1
    return f"{_GITHUB_REPO}/blob/{_LINKCODE_REF}/{rel_path}#L{start}-L{end}"
