function generate_e1_column()
%GENERATE_E1_COLUMN  Real-Breach robustness for the RV 2026 E1 pair set.
%
%   AUTO-GENERATED by extra/experiments/e1_divergence/breach_handoff.py from
%   the spec/signal registries (extra/experiments/registry/) -- do not edit
%   by hand; rerun the emitter instead. See HANDOFF.md in this directory.
%
%   Requires Breach (github.com/decyphir/breach) on the MATLAB path,
%   initialized via InitBreach. Run from the tidystl repository root:
%
%     >> addpath('extra/other_tools/breach'); generate_e1_column
%
%   Writes one CSV per case plus breach_meta.txt to
%   extra/experiments/e1_divergence/cache/breach_column/

    out = fullfile(pwd, 'extra', 'experiments', 'e1_divergence', 'cache', 'breach_column');
    if ~exist(out, 'dir')
        mkdir(out);
    end

    fprintf('E1 Breach column -> %s\n\n', out);
    write_meta(out);
    n = 0;

    % [baseline] predicate_gte: x >= 3
    n = n + eval_1sig(out, 'predicate_gte', ...
        [0 1 2 3 4], [5 2 4 1 6], ...
        'x[t] - 3 > 0');

    % [baseline] not_simple: not (x >= 0)
    n = n + eval_1sig(out, 'not_simple', ...
        [0 1 2 3 4], [3 -1 2 -4 5], ...
        'not (x[t] > 0)');

    % [baseline] and_two: (x >= 0) and (y >= 0)
    n = n + eval_2sig(out, 'and_two', ...
        [0 1 2 3 4], [3 -1 2 4 -2], [1 2 -1 3 5], ...
        '(x[t] > 0) and (y[t] > 0)');

    % [baseline] or_two: (x >= 0) or (y >= 0)
    n = n + eval_2sig(out, 'or_two', ...
        [0 1 2 3 4], [3 -1 2 4 -2], [1 2 -1 3 5], ...
        '(x[t] > 0) or (y[t] > 0)');

    % [baseline] combined_and_or: ((x >= 0) and (y >= 0)) or (z >= 0)
    n = n + eval_3sig(out, 'combined_and_or', ...
        [0 1 2 3 4], [1 -1 2 -2 3], [2 3 -1 1 -1], [-1 -1 -1 5 -1], ...
        '((x[t] > 0) and (y[t] > 0)) or (z[t] > 0)');

    % [baseline] always_sliding: G[0,2](x >= 0)
    n = n + eval_1sig(out, 'always_sliding', ...
        [0 1 2 3 4], [5 2 8 1 6], ...
        'alw_[0,2] (x[t] > 0)');

    % [baseline] always_boundary: G[1,2](x >= 0)
    n = n + eval_1sig(out, 'always_boundary', ...
        [0 1 2], [3 1 4], ...
        'alw_[1,2] (x[t] > 0)');

    % [baseline] eventually_sliding: F[0,2](x >= 0)
    n = n + eval_1sig(out, 'eventually_sliding', ...
        [0 1 2 3 4], [1 5 2 8 3], ...
        'ev_[0,2] (x[t] > 0)');

    % [baseline] eventually_offset: F[1,3](x >= 0)
    n = n + eval_1sig(out, 'eventually_offset', ...
        [0 1 2 3 4 5 6], [1 5 2 8 3 1 7], ...
        'ev_[1,3] (x[t] > 0)');

    % [baseline] eventually_boundary: F[1,2](x >= 0)
    n = n + eval_1sig(out, 'eventually_boundary', ...
        [0 1 2], [3 1 4], ...
        'ev_[1,2] (x[t] > 0)');

    % [baseline] until_basic: (x >= 0) U[0,3] (y >= 0)
    n = n + eval_2sig(out, 'until_basic', ...
        [0 1 2 3 4], [1 1 1 -1 -1], [-1 -1 2 2 2], ...
        '(x[t] > 0) until_[0,3] (y[t] > 0)');

    % [baseline] until_tight: (x >= 0) U[1,2] (y >= 0)
    n = n + eval_2sig(out, 'until_tight', ...
        [0 1 2 3 4], [1 1 1 -1 -1], [-1 -1 2 2 2], ...
        '(x[t] > 0) until_[1,2] (y[t] > 0)');

    % [baseline] until_never_sat: (x >= 0) U[0,4] (y >= 0)
    n = n + eval_2sig(out, 'until_never_sat', ...
        [0 1 2 3 4], [1 1 1 1 1], [-1 -1 -1 -1 -1], ...
        '(x[t] > 0) until_[0,4] (y[t] > 0)');

    % [baseline] until_boundary: (x >= 0) U[1,2] (y >= 0)
    n = n + eval_2sig(out, 'until_boundary', ...
        [0 1], [5 -5], [-1 2], ...
        '(x[t] > 0) until_[1,2] (y[t] > 0)');

    % [baseline] arith_sum: x + y >= 0
    n = n + eval_2sig(out, 'arith_sum', ...
        [0 1 2 3], [1 -2 3 -4], [2 3 -1 5], ...
        'x[t] + y[t] > 0');

    % [baseline] arith_difference: x - y >= 0
    n = n + eval_2sig(out, 'arith_difference', ...
        [0 1 2 3], [5 2 1 4], [3 3 2 0], ...
        'x[t] - y[t] > 0');

    % [divergence] div_boundary_F24: F[2,4](x >= 0)
    %   decision point: boundary rule
    n = n + eval_1sig(out, 'div_boundary_F24', ...
        [0 1 2], [-5 -1 3], ...
        'ev_[2,4] (x[t] > 0)');

    % [divergence] div_terminal_and: (x >= 0) and (y >= 0)
    %   decision point: terminal-step rule
    n = n + eval_2sig(out, 'div_terminal_and', ...
        [0 1 2], [5 5 -3], [5 5 -3], ...
        '(x[t] > 0) and (y[t] > 0)');

    % [divergence] div_interp_sparse: G[0.5,1.5](x > 0)
    %   decision point: interpolation
    n = n + eval_1sig(out, 'div_interp_sparse', ...
        [0 2 4], [-1 10 -1], ...
        'alw_[0.5,1.5] (x[t] > 0)');

    % [divergence] div_nonuniform_always: G[0,1](x > 0)
    %   decision point: signal model
    n = n + eval_1sig(out, 'div_nonuniform_always', ...
        [0 0.5 1.5 3 4], [0 3 1 -2 2], ...
        'alw_[0,1] (x[t] > 0)');

    % [divergence] div_equality: x == 3
    %   decision point: equality predicates
    n = n + eval_1sig(out, 'div_equality', ...
        [0 1 2 3 4], [3 2 4 3 1], ...
        'x[t] == 3');

    fprintf('\nE1 Breach column: %d/21 pairs OK\n', n);
end


%% ==================== Helper functions ====================
%% (mirrors generate_ground_truth.m; duplicated so this file is
%%  self-contained)

function ok = eval_1sig(out, name, time, x, formula)
    try
        BrSys = BreachTraceSystem({'x'});
        traj = struct('time', time, 'X', x);
        BrSys.AddTrace(traj);
        save_rob(BrSys, name, formula, time, out);
        ok = 1;
    catch e
        fprintf('  [FAIL] %s: %s\n', name, e.message);
        ok = 0;
    end
end

function ok = eval_2sig(out, name, time, x, y, formula)
    try
        BrSys = BreachTraceSystem({'x', 'y'});
        traj = struct('time', time, 'X', [x; y]);
        BrSys.AddTrace(traj);
        save_rob(BrSys, name, formula, time, out);
        ok = 1;
    catch e
        fprintf('  [FAIL] %s: %s\n', name, e.message);
        ok = 0;
    end
end

function ok = eval_3sig(out, name, time, x, y, z, formula)
    try
        BrSys = BreachTraceSystem({'x', 'y', 'z'});
        traj = struct('time', time, 'X', [x; y; z]);
        BrSys.AddTrace(traj);
        save_rob(BrSys, name, formula, time, out);
        ok = 1;
    catch e
        fprintf('  [FAIL] %s: %s\n', name, e.message);
        ok = 0;
    end
end

function save_rob(BrSys, name, formula, time, out)
    phi = STL_Formula(name, formula);
    [rob, tau] = STL_Eval(BrSys.Sys, phi, BrSys.P, BrSys.P.traj{1}, time);

    fpath = fullfile(out, [name '.csv']);
    fid = fopen(fpath, 'w');
    fprintf(fid, 'time,robustness\n');
    for i = 1:length(tau)
        fprintf(fid, '%.15g,%.15g\n', tau(i), rob(i));
    end
    fclose(fid);
    fprintf('  [OK] %s -> %d points\n', name, length(tau));
end

function write_meta(out)
    fid = fopen(fullfile(out, 'breach_meta.txt'), 'w');
    fprintf(fid, 'date: %s\n', datestr(now, 31));
    fprintf(fid, 'matlab: %s\n', version);
    try
        breach_dir = fileparts(which('InitBreach'));
        fprintf(fid, 'breach_path: %s\n', breach_dir);
        [st, rev] = system(['git -C "' breach_dir '" rev-parse HEAD']);
        if st == 0
            fprintf(fid, 'breach_commit: %s', rev);
        end
    catch
        fprintf(fid, 'breach_commit: (unavailable)\n');
    end
    fclose(fid);
end
